Register@thymeleaf
msk-itstep-org/jv31818-shelemekh pull request #5
Opened 2019-11-10 15:25 UTC by Ivanshelemeh

2019-11-10 15:27 UTC, Ivanshelemeh commented
please check new additional options , and give back an answear as soon as I can.

2019-11-12 14:27 UTC, const-se commented on .gitignore
> -/*.iml
Зачем вы удалили этот файл? Он очень важен!

2019-11-14 12:07 UTC, const-se requested changes
Исправьте, пожалуйста, проект в соответствии с замечаниями

2019-11-14 12:07 UTC, const-se commented on .gitignore
> -/*.iml
Необходимо вернуть этот файл назад. Он очень важен! С помощью этого файла контролируется игнорирование других папок и файлов, которые в репозиторий попасть не должны были!

2019-11-14 12:07 UTC, const-se commented on .idea/.name
> +app
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/compiler.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/encodings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/inspectionProfiles/Project_Default.xml
> +<component name="InspectionProjectProfileManager">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__antlr_antlr_2_7_7.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__ch_qos_logback_logback_classic_1_2_3.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__ch_qos_logback_logback_core_1_2_3.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__com_fasterxml_classmate_1_4_0.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__com_fasterxml_jackson_core_jackson_annotations_2_9_0.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__com_fasterxml_jackson_core_jackson_core_2_9_9.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__com_fasterxml_jackson_core_jackson_databind_2_9_9_3.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__com_fasterxml_jackson_datatype_jackson_datatype_jdk8_2_9_9.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__com_fasterxml_jackson_datatype_jackson_datatype_jsr310_2_9_9.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__com_fasterxml_jackson_module_jackson_module_parameter_names_2_9_9.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__com_jayway_jsonpath_json_path_2_4_0.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__com_vaadin_external_google_android_json_0_0_20131108_vaadin1.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__com_zaxxer_HikariCP_3_2_0.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__javax_activation_javax_activation_api_1_2_0.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__javax_annotation_javax_annotation_api_1_3_2.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__javax_persistence_javax_persistence_api_2_2.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__javax_transaction_javax_transaction_api_1_3.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__javax_validation_validation_api_2_0_1_Final.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__javax_xml_bind_jaxb_api_2_3_1.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__junit_junit_4_12.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__mysql_mysql_connector_java_8_0_17.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__net_bytebuddy_byte_buddy_1_9_16.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__net_bytebuddy_byte_buddy_agent_1_9_16.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__net_minidev_accessors_smart_1_2.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__net_minidev_json_smart_2_3.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_apache_logging_log4j_log4j_api_2_11_2.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__net_minidev_accessors_smart_1_2.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__net_minidev_json_smart_2_3.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_apache_logging_log4j_log4j_api_2_11_2.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_apache_logging_log4j_log4j_to_slf4j_2_11_2.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_apache_tomcat_embed_tomcat_embed_core_9_0_24.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_apache_tomcat_embed_tomcat_embed_el_9_0_24.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_apache_tomcat_embed_tomcat_embed_websocket_9_0_24.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_aspectj_aspectjweaver_1_9_4.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_assertj_assertj_core_3_11_1.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_attoparser_attoparser_2_0_5_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_dom4j_dom4j_2_1_1.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_flywaydb_flyway_core_5_2_4.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_hamcrest_hamcrest_core_1_3.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_hamcrest_hamcrest_library_1_3.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_hibernate_common_hibernate_commons_annotations_5_0_4_Final.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_hibernate_hibernate_core_5_3_11_Final.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_hibernate_validator_hibernate_validator_6_0_17_Final.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_javassist_javassist_3_23_2_GA.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_jboss_jandex_2_0_5_Final.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_jboss_logging_jboss_logging_3_3_3_Final.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_mockito_mockito_core_2_23_4.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_objenesis_objenesis_2_6.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_ow2_asm_asm_5_0_4.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_skyscreamer_jsonassert_1_5_0.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_slf4j_jul_to_slf4j_1_7_28.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_slf4j_slf4j_api_1_7_28.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_boot_spring_boot_2_1_8_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_boot_spring_boot_autoconfigure_2_1_8_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_boot_spring_boot_devtools_2_1_8_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_boot_spring_boot_starter_2_1_8_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on app.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .mvn/settings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_yaml_snakeyaml_1_23.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_xmlunit_xmlunit_core_2_6_3.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_unbescape_unbescape_1_1_6_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_thymeleaf_thymeleaf_spring5_3_0_11_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_thymeleaf_thymeleaf_3_0_11_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_thymeleaf_extras_thymeleaf_extras_java8time_3_0_4_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_spring_webmvc_5_1_9_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_spring_web_5_1_9_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_spring_tx_5_1_9_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_spring_test_5_1_9_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_spring_orm_5_1_9_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_spring_jdbc_5_1_9_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_spring_jcl_5_1_9_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_spring_expression_5_1_9_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_spring_core_5_1_9_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_spring_context_5_1_9_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_spring_beans_5_1_9_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_spring_aspects_5_1_9_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_spring_aop_5_1_9_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_data_spring_data_jpa_2_1_10_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_data_spring_data_commons_2_1_10_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_boot_spring_boot_test_autoconfigure_2_1_8_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_boot_spring_boot_test_2_1_8_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_boot_spring_boot_starter_web_2_1_8_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_boot_spring_boot_starter_tomcat_2_1_8_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_boot_spring_boot_starter_thymeleaf_2_1_8_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_boot_spring_boot_starter_test_2_1_8_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_boot_spring_boot_starter_logging_2_1_8_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_boot_spring_boot_starter_json_2_1_8_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_boot_spring_boot_starter_jdbc_2_1_8_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_boot_spring_boot_starter_data_jpa_2_1_8_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on .idea/libraries/Maven__org_springframework_boot_spring_boot_starter_aop_2_1_8_RELEASE.xml
> +<component name="libraryTable">
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on src/main/java/org/itstep/msk/app/controller/DemoController.java
> +    public String index(@RequestParam String name,
DemoController был создан как пример. Создайте свой собственный контроллер и перенесите в него свои методы. А этот нужно удалить

2019-11-14 12:07 UTC, const-se commented on src/main/java/org/itstep/msk/app/controller/DemoController.java
> +    @RequestMapping(value = "/main",method = RequestMethod.GET)
Вместо того, чтобы писать метод в аннотации @RequestMapping, следует использовать специально для этого существующую аннотацию @GetMapping

2019-11-14 12:07 UTC, const-se commented on src/main/java/org/itstep/msk/app/controller/DemoController.java
>      }
Что это такое?! Какова цель этого метода? Он не работает.

2019-11-14 12:07 UTC, const-se commented on src/main/java/org/itstep/msk/app/controller/DemoController.java
> +@RequestMapping("/main")
Зачем это тут?

2019-11-14 12:07 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/Customer.java
> +    private String phone_number;
Переименовать phone_number в phoneNumber

2019-11-14 12:07 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/Customer.java
> +    @OneToOne(optional = false)
Почему у покупателя связь на продукт один-к-одному?

2019-11-14 12:07 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/Product.java
> +    private double total_price;
Переименовать total_price в totalPrice

2019-11-14 12:07 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/Product.java
> +    @ManyToOne(fetch = FetchType.LAZY,cascade = CascadeType.ALL)
Почему здесь связь много-к-одному, однако, в Customer связь на продукт один-к-одному? Это ошибка

2019-11-14 12:07 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/Product.java
> +    private checklistCustomer checklist_customer;
Переименовать checklist_customer в checklistCustomer

2019-11-14 12:07 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/Product.java
> +   // private List<categoryForDogs> ctg_dog;
Зачем тут эти комментарии? Для кого они?

2019-11-14 12:07 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/Roles.java
> +public class Roles {
Имя класса должно быть в единственном числе!

2019-11-14 12:07 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/categoryForDogs.java
> +    private String special_quality;
Переименовать special_quality в specialQuality

2019-11-14 12:07 UTC, const-se commented on src/main/java/org/itstep/msk/app/entity/categoryForDogs.java
> +    List<Product> prod_list;
Переименовать prod_list в prodList

2019-11-14 12:07 UTC, const-se commented on src/main/java/org/itstep/msk/app/repository/CustomRepo.java
> +public interface CustomRepo extends JpaRepository<Customer,Integer> {
Называйте репозитории нормально - CustomerRepository, а не сокращенно. Это ухудшает качество кода

2019-11-14 12:07 UTC, const-se commented on src/main/resources/application.properties
> -server.address=@server_address@
Зачем вы меняли этот файл?!?! Да еще и свои параметры в репозиторий отправили! Никакой безопасности данных!
Эти все данные нужно было прописать в local.properties! Это было прописано в инструкции

2019-11-14 12:07 UTC, const-se commented on src/main/resources/db/migration/V0.0__init.sql
> -SELECT 1;
Зачем вы меняете файлы с миграциями? Их трогать нельзя

2019-11-14 12:07 UTC, const-se commented on target/classes/application.properties
> +server.address=127.0.0.1
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on target/classes/db/migration/V1.0__nurling1.sql
> +create table customer (
Необходимо удалить этот файл из репозитория

2019-11-14 12:07 UTC, const-se commented on target/classes/local.properties.dist
> +server_address=127.0.0.1
src/main/java/org/itstep/msk/app/entity/.gitignore → target/classes/db/migration/V0.0__init.sql

2019-11-14 12:07 UTC, const-se commented on target/classes/templates/demo.html
> +<!DOCTYPE html>
src/main/java/org/itstep/msk/app/entity/.gitignore → target/classes/db/migration/V0.0__init.sql

2019-11-14 12:11 UTC, const-se requested changes
Исправьте, пожалуйста, проект в соответствии с замечаниями

2019-11-26 14:13 UTC, merged